version: '3'
services:
    db:
        image: postgres:12.0
        environment:
            - POSTGRES_USER=postgres_user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres_db

    server:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
            - redis
        environment:
            DATABASE_URL: postgres://postgres_user:password@db:5432/postgres_db
            CELERY_BROKER_URL: redis://redis:6379
        ports:
            - 8000:8000
        volumes:
            - ./server:/server
    
    redis:
        image: redis:5.0.6
    
    celery:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        command: celery -A config worker -l info
        volumes:
            - ./server:/server
        depends_on:
            - db
            - redis
        environment:
            DATABASE_URL: postgres://postgres_user:password@db:5432/postgres_db
            CELERY_BROKER_URL: redis://redis:6379
    
    celery-beat:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        command: celery -A config beat -l info
        volumes:
            - ./server:/server
        depends_on:
            - db
            - redis
        environment:
            DATABASE_URL: postgres://postgres_user:password@db:5432/postgres_db
            CELERY_BROKER_URL: redis://redis:6379