# Generated by Django 2.2.6 on 2019-11-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cur', models.CharField(choices=[('CZK', 'Czech Republic Koruna'), ('EUR', 'Euro'), ('PLN', 'Polish Zloty'), ('USD', 'United States Dollar')], max_length=3, verbose_name='Currency for conversation')),
                ('to_cur', models.CharField(choices=[('CZK', 'Czech Republic Koruna'), ('EUR', 'Euro'), ('PLN', 'Polish Zloty'), ('USD', 'United States Dollar')], max_length=3, verbose_name='Result currency')),
                ('rate', models.DecimalField(decimal_places=12, max_digits=19, null=True, verbose_name='Current rate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
    ]
