# Generated by Django 2.2.6 on 2019-10-30 08:36

from django.db import migrations
from djmoney.contrib.exchange.backends import OpenExchangeRatesBackend
from djmoney.contrib.exchange.models import get_rate

from apps.rate.models import Currencies, Rate
from config.settings import OPEN_EXCHANGE_RATES_URL


def load_init_rates(*args, **kwargs):
    """Loads inintial rates of currencies"""
    backend = OpenExchangeRatesBackend(url=OPEN_EXCHANGE_RATES_URL)
    backend.update_rates()

    Rate.objects.bulk_create([
        Rate(
            from_cur=from_cur,
            to_cur=to_cur,
            rate=get_rate(from_cur, to_cur, backend=backend.name)
        ) for from_cur in Currencies.CURRENCIES
        for to_cur in Currencies.CURRENCIES
        if from_cur != to_cur
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_init_rates)
    ]
