# Generated by Django 2.2.6 on 2019-10-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20191030_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
    ]
