# Generated by Django 2.2.6 on 2019-11-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20191030_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=12, max_digits=19, null=True, verbose_name='Current rate'),
        ),
    ]
