# Generated by Django 2.2.6 on 2019-11-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20191101_0334'),
        ('rate', '0003_auto_20191030_1404'),
    ]

    operations = [
    ]
